# Generated by Django 4.1.7 on 2023-04-08 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_seller'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='seller',
            table='seller_tb',
        ),
    ]
